### ISSUE TITLE
We should have base classes so that we have unified inherited values

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#9]

**Comment by Lupus590** [comment]
Is this worth it? Could we use our urban camo as a base?

**Comment by Lexicon-Prime** [comment]
[MA:TGE] classes do not use inheritance properly, and so we'll need to find the lowest usable class for our equipment. Their config files do things like declaring an empty "ItemCore", which a mostly empty "Uniform_Base" inherits from; Yet every uniform entry has their own settings. My next comment will contain suggested classes to inherit from and their location / origin mod.

**Comment by Lexicon-Prime** [comment]
Helmets:
CH252 (Visor) -> [MA:TGE] Green CH252 `HaloInf_Marine_WDL_headgear` <- MA:TGE
CH252 (No Visor) -> [MA:TGE] Green CH252 `HaloInf_Marine_WDL_NV_headgear` <- MA:TGE
Any non-CH252 helmet -> `matching helmet model from MA` <- `MA_Helmet_Base` from Misriah Armory contains protection defaults

Uniforms:
[34th] Uniform -> `haloinfmar_U_WDL_uniform` <- MA:TGE
We are currently inheriting from `haloinfmar_U_GRFS_uniform`; There's no functional difference between WDL and GRFS, but if they update uniforms to inherit like helmets, it'd put us ahead of the change.

M56S_BDU (ODST) -> `MA_M56S_BDU` <- Misriah Armory

Vests:
Invisible Vests -> `MA_TGE_InvisVest` or `MA_TGE_ODST_InvisVest` <- MA:TGE
M56R Combat Armor -> `MA_M56R_Vest` <- Misriah Armory

Backpacks:
M56S Rucksack (No Radio) -> `MA_M56S_Rucksack` <- Misriah Armory
M56S Rucksack (Radio) -> `MA_M56S_Rucksack_Radio` <- Misriah Armory
The only functional differences are textures/hidden selections and if TFAR configs exist, so that's why the above was selected.

UNSC Hardcase Rucksack -> `Halo_Hardcase` <- MA:TGE
UNSC Radio Backpack -> `Halo_LR` <- MA:TGE

Balaclavas: In the future?
Weapons: We should approach these after we've handled armor/uniforms, if at all.

**Comment by Lexicon-Prime** [comment]
> Is this worth it? Could we use our urban camo as a base?

As for these questions; I'd say worth it, and I personally don't lean too heavily either way towards having a separate base or just inheriting from one of our classes. I will say having a separate base to inherit from is technically neater, but I think we would do fine inheriting from one we actually use.

**Comment by Lupus590** [comment]
Related: #13

**Comment by Lupus590** [comment]
We'll use our urban versions as bases.
